// challenges/week2/day09-weather-dashboard/frontend/src/App.vue
<template>
  <div style="padding: 2rem; font-family: sans-serif">
    <h1>Weather Dashboard</h1>

    <!-- TODO: city search input + button -->
    <input v-model="city" placeholder="Enter city..." @keyup.enter="fetchWeather" />
    <button @click="fetchWeather">Search</button>

    <div v-if="loading">Loading...</div>
    <div v-else-if="error" style="color:red">{{ error }}</div>
    <div v-else-if="weather">
      <!-- TODO: current conditions card -->
      <!-- TODO: 5-day forecast row (horizontal scroll) -->
      <pre>{{ weather }}</pre>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import axios from 'axios';

const city = ref('');
const weather = ref(null);
const loading = ref(false);
const error = ref(null);

async function fetchWeather() {
  if (!city.value) return;
  loading.value = true;
  error.value = null;
  try {
    // TODO: fetch from backend /weather?city={city}
    // const { data } = await axios.get(`http://localhost:8000/weather?city=${city.value}`);
    // weather.value = data;
  } catch (err) {
    error.value = err.response?.data?.detail || err.message;
  } finally {
    loading.value = false;
  }
}
</script>

// challenges/week2/day06-movie-search/frontend/src/App.jsx
import { useState, useEffect } from 'react';

const API = 'http://localhost:8000';

export default function App() {
  const [movies, setMovies] = useState([]);
  const [query, setQuery] = useState('');
  const [selected, setSelected] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    // TODO: fetch movies, pass ?q=query when query is set
    // fetch(`${API}/movies${query ? `?q=${query}` : ''}`)
  }, [query]);

  return (
    <div style={{ padding: '2rem', fontFamily: 'sans-serif' }}>
      <h1>Movie Search</h1>

      {/* TODO: search input — update query state on change */}
      <input
        type="text"
        placeholder="Search movies..."
        value={query}
        onChange={(e) => {/* TODO */}}
        style={{ padding: '0.5rem', width: '300px', marginBottom: '1rem' }}
      />

      {loading && <p>Loading...</p>}
      {error && <p style={{ color: 'red' }}>Error: {error}</p>}

      {/* TODO: render movie grid */}
      {/* TODO: on card click, fetch /movies/{id} and show detail */}

      {selected && (
        <div style={{ marginTop: '2rem', padding: '1rem', border: '1px solid #ccc' }}>
          <h2>Detail view</h2>
          {/* TODO: render selected movie detail */}
          <pre>{JSON.stringify(selected, null, 2)}</pre>
          <button onClick={() => setSelected(null)}>Close</button>
        </div>
      )}
    </div>
  );
}
