// challenges/week2/day06-movie-search/frontend/src/App.jsx
import { useState, useEffect } from 'react';

const API = 'http://localhost:8000';

export default function App() {
  const [movies, setMovies] = useState([]);
  const [query, setQuery] = useState('');
  const [selected, setSelected] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    // TODO: fetch movies, pass ?q=query when query is set
    // fetch(`${API}/movies${query ? `?q=${query}` : ''}`)
  }, [query]);

  return (
    <div style={{ padding: '2rem', fontFamily: 'sans-serif' }}>
      <h1>Movie Search</h1>

      {/* TODO: search input — update query state on change */}
      <input
        type="text"
        placeholder="Search movies..."
        value={query}
        onChange={(e) => {/* TODO */}}
        style={{ padding: '0.5rem', width: '300px', marginBottom: '1rem' }}
      />

      {loading && <p>Loading...</p>}
      {error && <p style={{ color: 'red' }}>Error: {error}</p>}

      {/* TODO: render movie grid */}
      {/* TODO: on card click, fetch /movies/{id} and show detail */}

      {selected && (
        <div style={{ marginTop: '2rem', padding: '1rem', border: '1px solid #ccc' }}>
          <h2>Detail view</h2>
          {/* TODO: render selected movie detail */}
          <pre>{JSON.stringify(selected, null, 2)}</pre>
          <button onClick={() => setSelected(null)}>Close</button>
        </div>
      )}
    </div>
  );
}

// challenges/week2/day07-employee-directory/frontend/src/App.vue
<template>
  <div style="padding: 2rem; font-family: sans-serif">
    <h1>Employee Directory</h1>

    <!-- TODO: department filter dropdown -->
    <!-- departments: All, Engineering, Design, Product, Marketing -->
    <select @change="/* TODO: update filter and refetch */">
      <option value="">All departments</option>
    </select>

    <!-- TODO: employee list -->
    <div v-if="loading">Loading...</div>
    <div v-else-if="error" style="color: red">{{ error }}</div>
    <div v-else>
      <!-- TODO: render employees as cards -->
      <pre>{{ employees }}</pre>
    </div>

    <!-- TODO: profile card for selected employee -->
    <div v-if="selected" style="margin-top: 2rem; padding: 1rem; border: 1px solid #ccc">
      <h2>Profile</h2>
      <pre>{{ selected }}</pre>
      <button @click="selected = null">Close</button>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import axios from 'axios';

const API = 'http://localhost:8000';
const employees = ref([]);
const selected = ref(null);
const department = ref('');
const loading = ref(false);
const error = ref(null);

async function fetchEmployees() {
  loading.value = true;
  try {
    // TODO: fetch employees, apply department filter if set
    // const params = department.value ? { department: department.value } : {};
    // const { data } = await axios.get(`${API}/employees/`, { params });
    // employees.value = data;
  } catch (err) {
    error.value = err.message;
  } finally {
    loading.value = false;
  }
}

onMounted(fetchEmployees);
</script>
